# Replica Set 1
apiVersion: v1
kind: Service
metadata:
  name: mongors2n1
  labels:
    app: mongors2n1
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongors2n1
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongors2n1
spec:
  serviceName: "mongors2n1"
  replicas: 1
  selector:
    matchLabels:
      app: mongors2n1
  template:
    metadata:
      labels:
        app: mongors2n1
    spec:
      containers:
      - name: mongors2n1
        image: indamutsa/mongo:v1.0.0
        command:
        - mongod
        - --shardsvr
        - --replSet
        - mongors2
        - --dbpath
        - /data/db
        - --port
        - "27017"
        - --bind_ip_all
        ports:
        - containerPort: 27017
        env:
        - name: TERM
          value: xterm
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongodb-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
# Replica 2          
---
apiVersion: v1
kind: Service
metadata:
  name: mongors2n2
  labels:
    app: mongors2n2
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongors2n2
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongors2n2
spec:
  serviceName: "mongors2n2"
  replicas: 1
  selector:
    matchLabels:
      app: mongors2n2
  template:
    metadata:
      labels:
        app: mongors2n2
    spec:
      containers:
      - name: mongors2n2
        image: indamutsa/mongo:v1.0.0
        command:
        - mongod
        - --shardsvr
        - --replSet
        - mongors2
        - --dbpath
        - /data/db
        - --port
        - "27017"
        - --bind_ip_all
        ports:
        - containerPort: 27017
        env:
        - name: TERM
          value: xterm
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongodb-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
       
---
# Replica Set 3  
apiVersion: v1
kind: Service
metadata:
  name: mongors2n3
  labels:
    app: mongors2n3
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongors2n3
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongors2n3
spec:
  serviceName: "mongors2n3"
  replicas: 1
  selector:
    matchLabels:
      app: mongors2n3
  template:
    metadata:
      labels:
        app: mongors2n3
    spec:
      containers:
      - name: mongors2n3
        image: indamutsa/mongo:v1.0.0
        command:
        - mongod
        - --shardsvr
        - --replSet
        - mongors2
        - --dbpath
        - /data/db
        - --port
        - "27017"
        - --bind_ip_all
        ports:
        - containerPort: 27017
        env:
        - name: TERM
          value: xterm
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongodb-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

